driver:
  name: ec2
  region: us-east-1
  subnet_id: subnet-276b7b08
  security_group_ids: ["sg-af481ee6"]
  image_id: ami-6871a115
  instance_type: t2.micro
  aws_ssh_key_id: harshanewssh
  associate_public_ip: true

transport:
  ssh_key: /home/harsharavuri/harshanewssh
  connection_timeout: 10
  connection_retries: 5
  username: ec2-user
  name: ssh

provisioner:
  name: chef_solo
  require_chef_omnibus: 13.8.3

verifier:
  name: inspec

platforms:
  - name: redhat-7
    block_device_mappings:
    - device_name: /dev/sdb
      ebs:
      volume_type: gp2
      virtual_name: test
      volume_size: 50
      delete_on_termination: true

suites:
  - name: default
    run_list:
    - recipe[webserver_test::default]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
